Fix compile with googletest versions newer than v1.12.0
Description:
cppbdd fails to compile with current googletest (newer than v1.12.0):

  thirdparty/cppbdd/include/cppbdd/gtestbdd.h:155:50: error: ISO C++ forbids
  declaration of ‘GTEST_DISALLOW_COPY_AND_ASSIGN_’ with no type [-fpermissive]
    155 |         GTEST_DISALLOW_COPY_AND_ASSIGN_(TestClass);\
        |                                                  ^

Root Cause:
Since googletest v1.12.0 the GTEST_DISALLOW_COPY_AND_ASSIGN_ macro was
removed by commit bf66935e ("Remove the legacy internal GTEST_DISALLOW_* macros", 2022-04-22).

Solution:
Replace the macro by plain C++ code (as was done by googletest itself).

Resolves: SWPF-241
Change-Id: Ic38be1adfaf0e0228bc79c029b52410d2d564d3a
Signed-off-by: Sandor Bodo-Merle <sandor.bodo-merle@rollingwireless.com>